
variables:
  Solution: src/LocalsInit.sln
  TestProject: src/LocalsInit.Tests/LocalsInit.Tests.csproj
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - task: Cache@2
        displayName: NuGet Cache
        inputs:
          key: 'NuGet | **/*.csproj, **/Directory.Build.props'
          restoreKeys: NuGet
          path: $(NUGET_PACKAGES)

      - task: MSBuild@1
        displayName: NuGet Restore
        inputs:
          solution: $(Solution)
          msbuildArguments: /v:m /t:Restore /bl:$(Build.ArtifactStagingDirectory)\restore.binlog

      - task: MSBuild@1
        displayName: Build
        inputs:
          solution: $(Solution)
          msbuildArguments: /v:m /t:Build
          configuration: Release
          maximumCpuCount: true

      - task: MSBuild@1
        displayName: NuGet Pack
        inputs:
          solution: $(Solution)
          msbuildArguments: /v:m /t:Pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
          configuration: Release
          maximumCpuCount: true

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: $(TestProject)
          arguments: --configuration Release
          nobuild: true
          testRunTitle: Release

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          ArtifactName: NuGet
