
name: Build
on: [push, pull_request]

env:
  DOTNET_NOLOGO: 1

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: NuGet Restore
        run: dotnet restore -nodeReuse:false src/LocalsInit.sln

      - name: Build
        run: dotnet build --configuration Release -nodeReuse:false --no-restore src/LocalsInit.sln

      - name: NuGet Pack
        run: dotnet pack --configuration Release -nodeReuse:false --no-build src/LocalsInit.sln

      - name: Test
        run: dotnet test --configuration Release -nodeReuse:false --no-build src/LocalsInit.sln

      - name: Upload NuGet
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: output/*.nupkg
